#!/usr/bin/env python3
"""gen-icon.py — draws the pixel-art damson icon and generates Resources/icon-source.svg.

32×32 pixel sprite (32px per cell → 1024×1024 master). A purple plum in the
Tokyo Night palette + leaf/stem + winking face + agent-style sparkles.
build-icon.sh converts this SVG to .icns.

After editing:  python3 scripts/gen-icon.py && bash scripts/build-icon.sh
"""
import math
import os

N = 32          # grid side length (cells)
CELL = 1024 // N  # cell pixel size

# ── Palette ─────────────────────────────────────────────────────────────
BG     = "#1a1b26"   # Tokyo Night background
RIM    = "#3b2766"   # plum outline/shadow
P_DK   = "#6b4caf"   # dark purple
P_MID  = "#8a68cf"   # mid purple
P_LT   = "#ab88e6"   # light purple
P_HI   = "#d3c2f4"   # highlight
LEAF_D = "#4f7a2c"   # leaf dark green
LEAF_L = "#9ece6a"   # leaf light green
STEM   = "#6b4a32"   # stem brown
EYE    = "#241f33"   # eyes/mouth (near black)
WHITE  = "#ffffff"   # eye glint / sparkle
BLUSH  = "#f7768e"   # blush

grid = [[None] * N for _ in range(N)]


def put(x, y, c):
    if 0 <= x < N and 0 <= y < N:
        grid[y][x] = c


# ── Plum body (ellipse) + shading ramp ─────────────────────────────────
cx, cy = 15.5, 18.0      # center
rx, ry = 10.0, 10.5      # radii
hx, hy = 12.0, 13.5      # highlight center (upper left)

for y in range(N):
    for x in range(N):
        ex = (x + 0.5 - cx) / rx
        ey = (y + 0.5 - cy) / ry
        e = ex * ex + ey * ey          # 1.0 = edge
        if e > 1.0:
            continue
        d = math.hypot(x - hx, y - hy)  # distance from highlight
        if e > 0.80:
            c = RIM
        elif d < 2.2:
            c = P_HI
        elif d < 4.4:
            c = P_LT
        elif d < 7.2:
            c = P_MID
        else:
            c = P_DK
        grid[y][x] = c

# ── Center cleft: slightly curved dark vertical line ───────────────────
for y in range(9, 28):
    bend = round(1.2 * math.sin((y - 9) / 19 * math.pi))
    xx = 16 + bend
    if grid[y][xx] not in (None, RIM):
        grid[y][xx] = P_DK
        # brighten the cell next to the cleft
        if grid[y][xx + 1] not in (None, RIM):
            grid[y][xx + 1] = P_LT

# ── Stem + leaf ────────────────────────────────────────────────────────
put(16, 8, STEM)
put(17, 7, STEM)
leaf = [
    (18, 6), (19, 5), (20, 5), (21, 5),
    (19, 6), (20, 6), (21, 6), (22, 6),
    (20, 7), (21, 7), (22, 7),
]
for (x, y) in leaf:
    grid[y][x] = LEAF_L
for (x, y) in [(19, 5), (20, 5), (21, 6), (22, 6), (22, 7)]:
    grid[y][x] = LEAF_D

# ── Upper-left glint (small gloss dot) ─────────────────────────────────
put(11, 12, P_HI)
put(12, 12, P_HI)
put(11, 13, P_HI)

# ── Face: round left eye + right wink ──────────────────────────────────
# left eye
for (x, y) in [(11, 18), (12, 18), (11, 19), (12, 19)]:
    grid[y][x] = EYE
put(11, 18, WHITE)            # glint
# right wink (downward-curved line)
for (x, y) in [(19, 19), (20, 18), (21, 18), (22, 19)]:
    grid[y][x] = EYE
# blush
for (x, y) in [(10, 21), (20, 21), (21, 21)]:
    grid[y][x] = BLUSH
# smiling mouth (upward-curved line)
for (x, y) in [(13, 22), (14, 23), (15, 23), (16, 23), (17, 23), (18, 22)]:
    grid[y][x] = EYE

# ── Agent sparkles (two 4-point stars) ─────────────────────────────────
def sparkle(x, y, big=True):
    put(x, y, WHITE)
    put(x - 1, y, WHITE); put(x + 1, y, WHITE)
    put(x, y - 1, WHITE); put(x, y + 1, WHITE)
    if big:
        put(x - 2, y, P_HI); put(x + 2, y, P_HI)
        put(x, y - 2, P_HI); put(x, y + 2, P_HI)

sparkle(25, 12, big=True)
sparkle(7, 25, big=False)

# ── SVG output ─────────────────────────────────────────────────────────
rects = []
for y in range(N):
    for x in range(N):
        c = grid[y][x]
        if c is None:
            continue
        rects.append(
            f'  <rect x="{x*CELL}" y="{y*CELL}" width="{CELL}" height="{CELL}" fill="{c}"/>'
        )

svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
  damson app icon — pixel-art plum character + agent sparkles.
  Generated by scripts/gen-icon.py. Do not edit directly; fix the script instead.
  build: python3 scripts/gen-icon.py && bash scripts/build-icon.sh
-->
<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges">
  <rect width="1024" height="1024" rx="180" ry="180" fill="{BG}"/>
{chr(10).join(rects)}
</svg>
'''

out = os.path.join(os.path.dirname(__file__), "..", "Resources", "icon-source.svg")
with open(os.path.normpath(out), "w") as f:
    f.write(svg)
print("wrote", os.path.normpath(out), f"({len(rects)} cells)")
